POST https://learn.codeit.kr/api/link-service/users
Content-Type: application/json

{
    "name": "코드잇",
    "email": "codeit1@example.com",
    "password": "password"
}

###
POST https://learn.codeit.kr/api/link-service/auth/login
Content-Type: application/json

{
    "name": "코드잇",
    "email": "codeit1@example.com",
    "password": "password"
}